### ISSUE TITLE
Improve messaging 

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2020]
- [x] Replace `cat()` with `message()` (or shortcut to the function) to allow users to suppress messages using `suppressMessages()` (#2019)
- [x] Consolidate `unused_dots()` and `check_dots()` (#1877).
- [x] Centralize value checks (#2009) 
- [x] Rename `friendly_class_undefined_message()` to `check_class()`
- [x] Centralize common error messages using https://github.com/quanteda/quanteda/blob/24c78db958ca500c5a96ac9fb5a262a4b343c97d/R/utils.R#L228-L242

**Comment by kbenoit** [comment]
Agree with all of these. But you will soon learn the joys of `revdep_check()`, since half of those functions are now defining functions in **quanteda.textstats** and **quanteda.textplots**. 😁 

I'm not sure we need to define all error messages in `message_error()`, just the ones that are reused.

**Comment by koheiw** [comment]
I do not promote `message_error()` too hard, but it is usually good to separate logic and view (c.f. [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller)).
